name: Autoupdate pre-commit configs and tflint aws plugin

on:
  # every sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write #require this to write to repo
  pull-requests: write #require this to create PR

jobs:
  auto-update:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: SPHTech-Platform/gha-pre-commit-autoupdate@main
        name: Update pre-commit config automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: SPHTech-Platform/gha-tflint-aws-plugin-autoupdate@main
        name: Update tflint aws plugin automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
